apiVersion: v1
kind: Secret
metadata:
  name: {{ include "harbor.registry" . }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: Opaque
data:
  {{- if not .Values.registry.credentials.htpasswdSecret.name }}
  REGISTRY_HTPASSWD: {{ .Values.registry.credentials.htpasswd | b64enc | quote }}
  {{- end }}
  {{- if not .Values.registry.secretSecret.name }}
  REGISTRY_HTTP_SECRET: {{ .Values.registry.secret | default (randAlphaNum 16) | b64enc | quote }}
  {{- end }}
  REGISTRY_REDIS_PASSWORD: {{ (include "harbor.redis.rawPassword" .) | b64enc | quote }}
  {{- if and (eq .Values.persistence.imageChartStorage.type "azure") (not .Values.persistence.imageChartStorage.azure.accountkeySecret.name) }}
  REGISTRY_STORAGE_AZURE_ACCOUNTKEY: {{ .Values.persistence.imageChartStorage.azure.accountkey | b64enc | quote }}
  {{- else if and (eq .Values.persistence.imageChartStorage.type "gcs") (not .Values.persistence.imageChartStorage.gcs.encodedkeySecret.name) }}
  GCS_KEY_DATA: {{ .Values.persistence.imageChartStorage.gcs.encodedkey | quote }}
  {{- else if eq .Values.persistence.imageChartStorage.type "s3" }}
  {{- if and (.Values.persistence.imageChartStorage.s3.accesskey) (not .Values.persistence.imageChartStorage.s3.accesskeySecret.name) }}
  REGISTRY_STORAGE_S3_ACCESSKEY: {{ .Values.persistence.imageChartStorage.s3.accesskey | b64enc | quote }}
  {{- end }}
  {{- if and (.Values.persistence.imageChartStorage.s3.secretkey) (not .Values.persistence.imageChartStorage.s3.secretkeySecret.name) }}
  REGISTRY_STORAGE_S3_SECRETKEY: {{ .Values.persistence.imageChartStorage.s3.secretkey | b64enc | quote }}
  {{- end }}
  {{- else if eq .Values.persistence.imageChartStorage.type "swift" }}
  {{- if not .Values.persistence.imageChartStorage.swift.passwordSecret.name }}
  REGISTRY_STORAGE_SWIFT_PASSWORD: {{ .Values.persistence.imageChartStorage.swift.password | b64enc | quote }}
  {{- end }}
  {{- if and (.Values.persistence.imageChartStorage.swift.secretkey) (not .Values.persistence.imageChartStorage.swift.secretkeySecret.name) }}
  REGISTRY_STORAGE_SWIFT_SECRETKEY: {{ .Values.persistence.imageChartStorage.swift.secretkey | b64enc | quote }}
  {{- end }}
  {{- if and (.Values.persistence.imageChartStorage.swift.accesskey) (not .Values.persistence.imageChartStorage.swift.accesskeySecret.name) }}
  REGISTRY_STORAGE_SWIFT_ACCESSKEY: {{ .Values.persistence.imageChartStorage.swift.accesskey | b64enc | quote }}
  {{- end }}
  {{- else if and (eq .Values.persistence.imageChartStorage.type "oss") (not .Values.persistence.imageChartStorage.oss.accesskeysecretSecret.name ) }}
  REGISTRY_STORAGE_OSS_ACCESSKEYSECRET: {{ .Values.persistence.imageChartStorage.oss.accesskeysecret | b64enc | quote }}
  {{- end }}
